### ISSUE TITLE
Significant indentation in single-quoted squiggly heredoc string is not preserved

### ISSUE THREAD

**Issue by mojavelinux** [oracle/truffleruby#1564]
In a squiggly heredoc string, Ruby is supposed to drop the indentation from all lines that matches the length of the indentation of the least indented line (excluding blank lines). This leaves significant indentation in tact. However, when single quotes are added to the heredoc marker, TruffleRuby drops all indentation, including significant indentation.

Working:

```rb
def fn
  <<~EOS
  a
    b
      c
  EOS
end

puts fn
#=> a
#=>   b
#=>     c
```

Not working:

```rb
def fn
  <<~'EOS'
  a
    b
      c
  EOS
end

puts fn
#=> a
#=> b
#=> c
```

It's interesting to note that the same problem exists in JRuby. See https://github.com/jruby/jruby/issues/4260.

**Comment by nirvdrum** [comment]
Thanks for checking against JRuby as well. JRuby ports MRI's parser and lexer to Java. We used to share those files when we were part of the JRuby project, but when forked away we ended up with our own copy of them. So, it's not too surprising that if JRuby has a problem like that that we've inherited it as well.

**Comment by deepj** [comment]
@eregon I guess this is already fixed.

```
$ ruby -v
truffleruby 20.2.0-dev-af4c22ac, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
$ ruby indent.rb
a
  b
    c
```

**Note: ** `indent.rb` is the code above

**Comment by eregon** [comment]
This is not fixed yet, but we should be able to import the fix from JRuby 9.2.8.0: https://github.com/jruby/jruby/commit/76eb532f1a1fdb41257dce8b4226e4289938cf9a

We should probably look into importing all changes in JRuby 9.2.8.0 related to the parser, but not sure how easy/hard that is to update since we have some changes there.

**Comment by deepj** [comment]
@eregon yeh, I tried the example above and it was ok, but then I tried the example in the JRuby issue, and it wasn't ok. That was the reason why I removed my comment.

**Comment by eregon** [comment]
Please lave an extra comment in that case :)
I tried the `Not working:` example above and that still fails.

**Comment by mojavelinux** [comment]
@deepj I may have phrased it in a confusing way. It's the second sample that fails. The first example is just a reference for what already works.

**Comment by eregon** [comment]
Fixed in 3fb12623c0c2c39a0f765ce48bee1e920805adc3, thanks for the report.
