### ISSUE TITLE
BigDecimal.inspect behaviour with active_record

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#1960]
Under truffleruby 20.1.0-dev-3de4af67, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]

```
ruby -e "require 'active_record'; amount = BigDecimal.new('444.44'); puts amount;puts 'Amount    %s' % amount.inspect"
BigDecimal.new is deprecated; use BigDecimal() method instead.
444.44
Amount    444.44
```

but with MRI

```
ruby -e "require 'active_record'; amount = BigDecimal.new('444.44'); puts amount;puts 'Amount    %s' % amount.inspect"
-e:1: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
444.44
Amount    0.44444e3
```

Requiring `bigdecimal` directly results in consistent output!

**Comment by norswap** [comment]
(Probably) relevant rails file: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/big_decimal/conversions.rb

**Comment by norswap** [comment]
Can't get it to reprod by using simply:

```
require 'bigdecimal'


p BigDecimal('444.444')
# prints "0.444444e3"

module ActiveSupport
  module BigDecimalWithDefaultFormat #:nodoc:
    def to_s(format = "F")
      super(format)
    end
  end
end

﻿BigDecimal.prepend(ActiveSupport::BigDecimalWithDefaultFormat)

p BigDecimal('444.444')
# prints 444.444
```

I think this might already have been fixed.
Could you:

- Try the above using the version you're currently using.
- If it fails, update to master HEAD and see if that fixes it.

**Comment by petenorth** [comment]
I just re-ran using my test repo:

https://github.com/petenorth/decimal-rounding-ruby/runs/511809541?check_suite_focus=true

It is the fifth step in the workflow. I still see a different behaviour.

**Comment by norswap** [comment]
Are you sure you're using the latest version? I'm getting:

```
$ ruby -v
truffleruby 20.1.0-dev-d31d48fe, like ruby 2.6.5, Interpreted JVM [x86_64-darwin]
$ ruby -e "require 'active_record'; amount = BigDecimal.new('444.44'); puts amount;puts 'Amount %s' % amount.inspect"
BigDecimal.new is deprecated; use BigDecimal() method instead.
444.44
Amount 444.44
```

**Comment by norswap** [comment]
Ah I see, I thought it was TruffleRuby generating `0.44444e3` and ignoring the advice. Back to investigation.

**Comment by petenorth** [comment]
> It's unfortunate that the way we do it seems better, but compatibility first!

Fair enough!

**Comment by petenorth** [comment]
@norswap have confirmed that it is fixed in the latest build, thanks.

**Comment by eregon** [comment]
Fixed by 829e8150ee7f9b9d4e6ae5a3ba926d9ace45b83d
